- src/10-serial-communication/README.md
2 links on the '"Serial" communication' page were resulting in 404s
> Fixed some broken links

- src/07-registers/README.md
- src/07-registers/bad-address.md
- src/07-registers/optimization.md
- src/07-registers/src/main.rs
- src/07-registers/type-safe-manipulation.md
- src/08-leds-again/README.md
- src/08-leds-again/power.md
1. A few typos, e.g. peripheral vs peripheralS.
2. Made sure the code in 07/README matched the actual code.
3. Fixed a few comments where it said 'turn on' when it was actually 'turn off'.
4. A few wording fixes.
> Fix some wording in 07 and 08

- src/14-i2c/README.md
Page number pointed to the end of the section instead of the beginning of the section.
> Updated page number

- src/17-async-io-the-future/my-solution.md
The borrow checker would like mutable references. Closes #57.
> Requires mutable references.

- src/09-clocks-and-timers/initialization.md
- src/09-clocks-and-timers/putting-it-all-together.md
First of all, thanks for your great job in the world of programming microcontrollers in rust!
I believe the bit set and clear were mixed up. The registers are explained in the page 678 of the user manual.
Thanks!
> Fix in chapter 9: set OPM and clear CEN (for one pulse mode)

- src/09-clocks-and-timers/one-shot-timer.md
This corrects the page numbers per the version of the reference manual linked below.
https://www.st.com/content/ccc/resource/technical/document/reference_manual/4a/19/6e/18/9d/92/43/32/DM00043574.pdf/files/DM00043574.pdf/jcr:content/translations/en.DM00043574.pdf
> Correct page numbers in 09-clocks-and-timers

- src/15-led-compass/.gdbinit
This fix causes the project to break at the normal start of the user's `main` function as it does in all of the other examples, allowing `layout src` to immediately work.
> Fix LED Compass project GDB breakpoint

- ci/script.sh
this catches / prevents build errors in the bookshelf repo like
https://travis-ci.org/rust-embedded/bookshelf/builds/433522599
> run linkchecker simulating the bookshelf layout

- src/05-led-roulette/build-it.md
Explain as provided build command and Cargo.toml file will handle turning off optimizations and improve the verbiage about this build doesn't blink the lights.
> Minor build-it.md changes

- ci/install.sh
> Force use of mdbook 0.2.1 as 0.2.2 is broken for now

- src/07-registers/bad-address.md
I see 'ef' used correctly everywhere else in this section. Looks like
this one just got missed in 2a213e70ebb763388cf344d3c678fe42dc7113d8.
> Switch '_ef' reference to 'ef' in GDB session example

- src/03-setup/README.md
- src/README.md
- src/explore.md
Clicking these links does forward the browser to the correct GitHub
repository but I thought maybe it would be better to just update the
URLs to the new location of these repositories.
> Update links moved from japaric to rust-embedded

- src/05-led-roulette/.cargo/config
- src/05-led-roulette/the-challenge.md
- src/06-hello-world/.cargo/config
- src/06-hello-world/README.md
- src/07-registers/.cargo/config
- src/08-leds-again/.cargo/config
- src/09-clocks-and-timers/.cargo/config
- src/11-usart/.cargo/config
- src/14-i2c/.cargo/config
- src/15-led-compass/.cargo/config
- src/16-punch-o-meter/.cargo/config
The diff in 06-hello-world/README.md for changes to be made to
.cargo/config are based off of an older version of the config file than
what is found in the repository currently.
> Update .cargo/config diff baseline

- src/11-usart/README.md
- src/16-punch-o-meter/gravity-is-up.md
* I don't see the IOW acronym enough to know what it means without
looking it up. I thought others might have the same issue so I
expanded it. In the same sentence I changed what I think was an
incorrect spelling of "whereas".
* I changed the text describing the itmdump of accelerometer readings
to indicate that the actual output seen by the user if they run the
same code won't be exactly as seen here.
> A few documentation changes

- src/README.md
This is my initial attempt to address issue #129 opened by @adamgreig
to have links back to the bookshelf added to the front page. I am
not sure if this is what you were looking for but I thought I would
give it a try. Let me know what you think.
> Link back to bookshelf for other embedded resources

- src/02-requirements/README.md
- src/04-meet-your-hardware/README.md
- src/05-led-roulette/flash-it.md
- src/05-led-roulette/the-challenge.md
- src/06-hello-world/README.md
- src/10-serial-communication/loopbacks.md
- src/10-serial-communication/nix-tooling.md
- src/10-serial-communication/windows-tooling.md
- src/11-usart/README.md
- src/12-bluetooth-setup/README.md
- src/12-bluetooth-setup/at-commands.md
- src/12-bluetooth-setup/loopback.md
- src/13-serial-over-bluetooth/README.md
- src/15-led-compass/README.md
- src/15-led-compass/calibration.md
- src/15-led-compass/take-1.md
- src/16-punch-o-meter/README.md
Cancelled a previous PR #121 in favor of this one. To make it cleaner using a new branch instead of my master.
#123 Also pointed to this issue.
> To fix links with correct reference to assets folder

- src/03-setup/README.md
> To fix 03-setup/Readme.md references to next section links

- ci/script.sh
- src/02-requirements/README.md
- src/03-setup/README.md
- src/03-setup/linux.md
- src/03-setup/macos.md
- src/03-setup/verify.md
- src/03-setup/windows.md
- src/04-meet-your-hardware/README.md
- src/05-led-roulette/debug-it.md
- src/05-led-roulette/flash-it.md
- src/05-led-roulette/the-challenge.md
- src/06-hello-world/README.md
- src/10-serial-communication/README.md
- src/10-serial-communication/loopbacks.md
- src/10-serial-communication/nix-tooling.md
- src/10-serial-communication/windows-tooling.md
- src/11-usart/README.md
- src/12-bluetooth-setup/README.md
- src/12-bluetooth-setup/at-commands.md
- src/12-bluetooth-setup/linux.md
- src/12-bluetooth-setup/loopback.md
- src/13-serial-over-bluetooth/README.md
- src/15-led-compass/README.md
- src/15-led-compass/calibration.md
- src/15-led-compass/take-1.md
- src/16-punch-o-meter/README.md
- src/README.md
- src/appendix/1-general-troubleshooting/README.md
This PR pools together PRs #130 and #131 from @ChouzArt and adds 2 more commits that I created to correct other failing links missed by the first 2 and to modify the Travis verification steps to skip the checking of print.html - @ChouzArt has previously pointed out that https://github.com/rust-lang-nursery/mdBook/issues/789 causes mdbook to generate an incorrect print.html file when relative links are used in the book content. Skipping verification of print.html during Travis runs means that we will still have a bad image links in print.html but the main Discovery book pages will have working images again and they will show up here on GitHub as well. I realize that this isn't a perfect solution but I thought that people might find it better than the current situation.
The main reason I am …
> Attempt to fix broken image links in Discovery book

- src/README.md
Documentation was recently moved to docs.rust-embedded.org and the old
links on this page now result in 404 errors.
> Update bookshelf URLs to new location

- src/03-setup/linux.md
openocd is not available in official repositories for Arch Linux, this edit gives readers two options for installing the package on their system.
> Added openocd installation guide for Arch Linux

- src/03-setup/README.md
These links were not up to date.
> Fixed some broken URLs

- src/10-serial-communication/nix-tooling.md
I've gone through this guide once or twice and this has tripped me up several times. On mac you shouldn't try to locate the FTDI device using `dmesg`, but the previous guide seemed to lead you to that.
I've moved the mac note higher in the docs as well as provided a command to actually find it on macOS.
> Clarify how to locate FTDI device on macOS

- src/03-setup/linux.md
- src/05-led-roulette/flash-it.md
I recently had the pleasure of working my way through the Discovery book. The only stumbling block was that I couldn't find the `gdb-arm-none-eabi` package on Ubuntu 18.04/18.10. I later found that The Embedded Rust Book had more up to date instructions on this part. This PR copies those improvements from `book` to `discovery`.
This should fix #91.
> Update gdb instructions for Ubuntu 18.04+

- src/07-registers/README.md
I added a missing word ("a") to the section providing a definition of register.  The goal was to improve readability.
> Added a missing word to the 07-registers README

- src/11-usart/my-solution.md
Either a `break` or `buffer.clear()` is needed here to ensure the buffer is properly cleared between each server response.
> Adding break to clear buffer.

- src/03-setup/README.md
Lower in the steps `0.3.1` is used, so I presume this is the correct version.
> Fix required itmdump version to match install steps

- src/03-setup/linux.md
This reverts commit f712448bb524aba999d6fe6bf850745d17700483.
https://github.com/rust-embedded/discovery/pull/173#issuecomment-466752998
> Revert "Recommend openocd-git package instead of openocd"

- src/07-registers/openocd.gdb
UserHardFault renamed to HardFault in cortex-m-rt:
https://github.com/rust-embedded/cortex-m-rt/commit/790e42477ca21d6d0a07270049c3747c7c316f4b
> Chapter 7: Breakpoint should be set on HardFault

- src/02-requirements/README.md
I was getting started with the discovery book and still had two old
unmarked Mini USB cables laying around. Unfortunately none of them
were working.
I don't know too much about the USB standards, but one reason
may be that these cables only support charging without data transfer.
I think it would be good to mention this here, if people go out and buy
new cables.
> Requirements: USB cables need data transfer

- src/14-i2c/read-a-single-register.md
Currently documentation refers to wrong page number here in Ch 14.3 which states that "Section 28.7 I2C registers - Page 873 - Reference Manual". I fixed it with page number 868.
> Fixed I2C registers page number of reference manual in Ch 14.3

- ci/install.sh
Ref #136 
Closes #137 
`ci/install.sh` is updated based on [book's copy](https://github.com/rust-embedded/book/blob/master/ci/install.sh), but preserving the rustup line and target specification.
> Update CI install to use latest mdbook, reverting 09753a1

- book.toml
- custom.css
- src/05-led-roulette/the-challenge.md
- src/07-registers/README.md
- src/14-i2c/README.md
- src/14-i2c/the-general-protocol.md
- src/15-led-compass/take-1.md
- src/15-led-compass/take-2.md
Some images with alpha channel, are unreadable when a dark theme is applied. This commit adds a custom image style, named `white_bg`, that can be used to fix this issue.
The style is very simple, and adds two features:
- white background,
- a small padding around the image
> Feat: add custom formatting for images

- src/03-setup/windows.md
Binary releases are now at home at the xPack project.
> Updated the link for OpenOCD

- src/03-setup/README.md
The `itm` is in the book formatted as code. Therefore, it is not intuitive to click on the link and to be redirected to the cargo page. In addition, the crate doesn't show how to get it up & running.
I suggest to add a note with `cargo install itm` next to the `itmdump` link.
> Make `itmdump` more visible (second try)

- src/SUMMARY.md
Section 12.3 (AT commands) exists, but is not in the sidebar menu (SUMMARY.md)
> Add section [Bluetooth setup] -> [AT commands]

- src/06-hello-world/README.md
Add missing instruction to launch `openocd` and fix information about `.gdbinit`.
> Chapter 06: Update README

- src/03-setup/macos.md
The `gcc-arm-embedded` was deleted from the cask (pease see #167) and the setup command won't work. Closest working solution seems to be using formulae from [ARMmbed/homebrew-formulae](https://github.com/armmbed/homebrew-formulae).
> Update macOS setup instructions for ARM toolchain.

- src/02-requirements/README.md
Was wondering if this small addition to the "knowledge" requirements would be useful to add. I think having a full-on tutorial (even something in the appendix) for these would be a bit out of scope for this tutorial, but sometimes it helps to just give something a name for people to google later.
I'm not familiar with how technical book layouts like this works; is there some way that the code sample in this PR needs to be put into another file (e.g., so that there can be an automated check that the code still compiles), or would that only need to be reserved for larger, more important code samples?
> Add knowledge requirement for hex and bitwise operations.

- src/04-meet-your-hardware/README.md
In the first in a series of changes I'm proposing to try to help resolve issue #199, this changes the book's "Meet Your Hardware" in a few ways.
While technically the original bullet points listed that the microcontroller was one of the components of the board, this hopefully makes a bit more clear that really they are two completely separate entities. This should especially help in Chapter 7 when readers are asked to jump between different reference manuals; understanding when to look at the reference manual of the board vs the microcontroller requires a solid understanding of the difference between these two products.
Also, given the book's expectation that the user has no previous knowledge of embedded development, I felt that listing specs (like RAM and Flash) probably only end up …
> Removed overwhelming info, added context to "Meet your Hardware"

- src/01-background/README.md
- src/03-setup/README.md
- src/03-setup/linux.md
- src/03-setup/verify.md
- src/04-meet-your-hardware/README.md
- src/05-led-roulette/build-it.md
- src/05-led-roulette/flash-it.md
- src/06-hello-world/README.md
- src/10-serial-communication/README.md
- src/10-serial-communication/loopbacks.md
- src/10-serial-communication/nix-tooling.md
- src/10-serial-communication/windows-tooling.md
- src/11-usart/README.md
- src/11-usart/buffer-overrun.md
- src/11-usart/echo-server.md
- src/11-usart/receive-a-single-byte.md
- src/11-usart/send-a-single-byte.md
- src/11-usart/send-a-string.md
- src/12-bluetooth-setup/README.md
- src/12-bluetooth-setup/at-commands.md
- src/12-bluetooth-setup/linux.md
- src/12-bluetooth-setup/loopback.md
- src/13-serial-over-bluetooth/README.md
- src/SUMMARY.md
- Change `laptop/PC` into more general `computer`
- Change the short `micro` into `microcontroller`
- Properly escape `*` character in Markdown files
> Batch of styling and formatting changes

- src/07-registers/type-safe-manipulation.md
The STM32f3 reference manual contains the following: 
> Bits 31:16 Reserved, must be kept at reset value.
on page 239, section 11.4.6
> Minor typo in type-safe-manipulation.md

- src/09-clocks-and-timers/for-loop-delays.md
I think this was meant to say `80MHz` (Rounded up from `72MHZ` speed of the STM32F303VC?).
> Fix clock speed typo

- src/09-clocks-and-timers/for-loop-delays.md
Original PR to fix typo was  #247, which was merged but incorrect. PR #248 was closed after determining the correct clock speed is `72MHz`, not 80 or 8.
> Change clock speed to 72MHz

- src/03-setup/README.md
I have an error when using version the old one (0.1.4) similar to https://github.com/rust-embedded/discovery/issues/184, when I'm upgrade to the latest one (0.3.0) it's resolved. On Windows 10 HS v2004.
> Using the latest version (0.3.0) of cargo-binutils

- src/05-led-roulette/debug-it.md
- src/SUMMARY.md
- src/appendix/2-how-to-use-gdb/README.md
> Gdb usage appendex

- src/appendix/1-general-troubleshooting/README.md
My F3 seemed to come with the stlink-v2 and not the stlink-v2-1 config interface which caused the same "Error: open failed" output.
I suggest to hint to try the older version in that case.
I've also separated Cause and Fix headings because I didn't know how to phrase it otherwise.
Related to https://github.com/rust-embedded/book/issues/263.
> appendix: add hint about ST-LINK config version

- src/06-hello-world/README.md
I got slightly confused by the note saying that the datasheet was wrong
about the solder bridge because from how I read it, it says:
I wonder if this might have been fixed in the datasheet in the meantime?
> 06-hello-world: change note about solder bridge

- book.toml
This will show a GitHub icon in the website that links to the repo
> book.toml: add link to GitHub repo

- src/07-registers/type-safe-manipulation.md
The last code block of the Type Safe Manipulation section contains
invalid flags because they are missing a dash. Thankfully cargo is
intelligent enough to provide correct suggestions.
Suggestion from cargo:
```console
llvm-objdump: Unknown command line argument '-no-show-raw-insn'.  Try: '/home/itme/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objdump --help'
llvm-objdump: Did you mean '--no-show-raw-insn'?
llvm-objdump: Unknown command line argument '-print-imm-hex'.  Try: '/home/itme/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objdump --help'
llvm-objdump: Did you mean '--print-imm-hex'?
```
> 07-registers: Fix cargo objdump example

- src/appendix/1-general-troubleshooting/README.md
On my machine (a Mac) i encountered this error every time i went to start up openocd according to the Verify the Installation instructions in chapter 3. For me, it was because some java process was running on port 4444. I went the Solution A route and killed that process.
For the typical rust-embedded user this troubleshooting step may be quite obvious. But when i did not see my particular error message in the troubleshooting section, i got a little lost wondering if any number of way less likely scenarios were affecting my device.
Because i don't have access to a Linux or Windows machine, i have not included instructions on how to find and kill processes using particular ports on those platforms. I thought of copy-pasting instructions from the internet, but i would not be able to verify …
> Adds details of how to assess and fix an "Address already in use" error

- src/08-leds-again/openocd.gdb
- src/09-clocks-and-timers/openocd.gdb
- src/11-usart/openocd.gdb
- src/14-i2c/openocd.gdb
- src/15-led-compass/openocd.gdb
- src/16-punch-o-meter/openocd.gdb
UserHardFault was renamed to HardFault in Feb. 2019:
https://github.com/rust-embedded/cortex-m-rt/commit/790e42477ca21d6d0a07270049c3747c7c316f4b
Also, 07-registers was already changed, also in Feb. 2019:
https://github.com/winksaville/rust-embedded-discovery/commit/1b0979183f348c13c7adb04c2ff10e8956f7e496
I propose this PR to fix the other references within the discovery book.
> Change references to UserHardFault to HardFault in openocd.gdb

- src/07-registers/optimization.md
- src/09-clocks-and-timers/nop.md
- The long argument name options specified to `objdump` require
two dashes '--'.
Fixes https://github.com/rust-embedded/discovery/issues/284 .
> Fix specifying options in (mis)Optimization

- src/07-registers/bad-address.md
- As mentioned in PR #282, references to `UserHardFault`
should be changed to `HardFault` since it was changed in the
cortex-m-rt crate.
- This change updates the text and referenced source snippets
in the debugger to refer to `HardFault` in Chapter 7.3.
> Update UserHardFault to HardFault text in Ch 7.3

- src/03-setup/README.md
While following the instructions for cargo-binutils in 03-setup
the `cargo size -- -version` caused an error when following the
instructions:
``` console
$ cargo size -- -version
error: Error during execution of `cargo metadata`: error: could not find `Cargo.toml` in `C:\Users\wink` or any parent directory
```
The cause of the error is that you're not told to  be in a rust project
directory.
The solution I've chosen is to create a rust bin project, cd into the
project, run it and then do the `cargo size -- -version`.
> Tweak testing cargo-binutils

- ci/install.sh
This would at least make our publication step work again even though still on Travis CI.
See #289
> Fix installing dateutil since it is now a dependency of the GHP import script

- src/06-hello-world/.cargo/config
- src/06-hello-world/Cargo.toml
- src/06-hello-world/README.md
- src/06-hello-world/auxiliary/Cargo.toml
- src/06-hello-world/auxiliary/src/lib.rs
- src/06-hello-world/openocd.gdb
- src/06-hello-world/panic.md
Converted lib.rs, Cargo.toml to use stm32f3_discovery.
.cargo/config:
I also, found that I would forget to to use `--target` when
building and running using cargo so set the default build target
to thumbv7em-none-eabihf
openocd.cfg:
Since the monitor lines are quite long and also easy to mistype or
forget to do I enhanced the file with the new lines and commented
on each of the lines.
README.md
Update to reflect the above changes.
> New-06-hello-world

- src/05-led-roulette/README.md
- src/05-led-roulette/auxiliary/Cargo.toml
- src/05-led-roulette/build-it.md
- src/05-led-roulette/debug-it.md
- src/05-led-roulette/flash-it.md
- src/05-led-roulette/the-challenge.md
- src/05-led-roulette/the-led-and-delay-abstractions.md
Cargo.toml to use stm32f3-discovery v0.6.0 crate.
Update `.md` files with additional information and to make console
commands amenable to copy/paste operations.
> Update 05 led-roulette

- .travis.yml
Hopefully this will allow us to merge #308
> Increase Travis no-output waiting time

- src/.cargo/config.toml
- src/05-led-roulette/debug-it.md
- src/05-led-roulette/flash-it.md
- src/05-led-roulette/the-challenge.md
- src/05-led-roulette/the-led-and-delay-abstractions.md
- src/06-hello-world/.cargo/config
- src/07-registers/.cargo/config
- src/08-leds-again/.cargo/config
- src/09-clocks-and-timers/.cargo/config
- src/11-usart/.cargo/config
- src/14-i2c/.cargo/config
- src/15-led-compass/.cargo/config
- src/16-punch-o-meter/.cargo/config
- src/openocd.gdb
Instead of every chapter having its own copy of the cargo configuration
and openocd.gdb files this change creates a shared set. This will make it
much easier for the user of the discovery book to handle the situation
where their Arm gdb is NOT arm-none-eabi-gdb. As only the shared copy
of .cargo/config.toml will have to be modified.
Also src/05-led-roulette is updated to take advantage of this and I
will go through each of the other chapters changing them to use
the shared set.
I also needed to comment out the rustflags variable in all of the config
files as I'd get an error executing ci/script.sh:
ry.x:5: region 'FLASH' already defined
>>>   FLASH : ORIGIN = 0x08000000, LENGTH = 256K
>>>
> Add shareable instances of config.toml and openocd.gdb

- src/03-setup/linux.md
My device has identical `idProduct` and `idVendor` values to the one used for the documentation.
`lsusb | grep STM` outputs:
```
Bus 003 Device 033: ID 0483:374b STMicroelectronics ST-LINK/V2.1
```
The verbose version, `lsusb -v`, outputs
```
...
idVendor           0x0483 STMicroelectronics
idProduct          0x374b ST-LINK/V2.1
...
```
Which leads me to the belief that the first value in the short output is the vendor and the latter is the product.
> Fix small typo in Linux setup

- src/11-usart/auxiliary/Cargo.toml
- src/14-i2c/auxiliary/Cargo.toml
- src/15-led-compass/auxiliary/Cargo.toml
Fix it by sticking with cortex-m 0.5.6.
See discussion at #327.  This is a much simpler (and certainly more hackish) solution than is proposed in #267.  But it doesn't require `unsafe` code nor a custom `memory.x` file, and might fill the gap until the book is rewritten.
> Fix breaking change in  cortex-m 0.5.11.

- src/09-clocks-and-timers/auxiliary/Cargo.toml
- src/09-clocks-and-timers/auxiliary/src/lib.rs
- src/09-clocks-and-timers/putting-it-all-together.md
- src/09-clocks-and-timers/src/main.rs
- src/11-usart/auxiliary/Cargo.toml
- src/11-usart/auxiliary/src/lib.rs
- src/11-usart/buffer-overrun.md
- src/11-usart/my-solution.md
- src/11-usart/src/main.rs
- src/14-i2c/auxiliary/Cargo.toml
- src/14-i2c/auxiliary/src/lib.rs
- src/14-i2c/read-several-registers.md
- src/14-i2c/src/main.rs
- src/14-i2c/the-solution.md
- src/15-led-compass/auxiliary/Cargo.toml
- src/15-led-compass/auxiliary/src/lib.rs
- src/15-led-compass/solution-1.md
- src/15-led-compass/solution-2.md
- src/15-led-compass/take-1.md
- src/15-led-compass/take-2.md
- src/16-punch-o-meter/auxiliary/Cargo.toml
- src/16-punch-o-meter/auxiliary/src/lib.rs
Fix #338 #340 
It looks like these problems are caused by multiple versions. I have no idea of the underlying reasons, but I think the simplest workaround is to keep one version. So I remove f3 crate which depends on `cortex-m v0.5.6` to fix it.
There are also the same problems in chapter 11,14,15. But it seems more complex, as I'm a newbie in this field, and I'm still learning :-). So I only submit this to fix chapter 9. Thanks a lot.
> Fix compile error

- src/16-punch-o-meter/auxiliary/src/lib.rs
I would prefer the example code not to contain unused results. This cleans up the actually one and only warning on an unused result.
```bash
$ cargo build --target thumbv7em-none-eabihf
[...]
warning: unused `Result` that must be used
--> src/16-punch-o-meter/auxiliary/src/lib.rs:38:5
|
38 |     nss.set_high();
|     ^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: this `Result` may be an `Err` variant, which should be handled
warning: 1 warning emitted
[...]
```
> Clean up warning on unused result

- .github/workflows/ci.yml
This is a remake of https://github.com/rust-embedded/discovery/pull/255 for the actual GitHub Actions.
The need for keeping this exemption around no longer exists since a while. Let's remove it and pave the way for closing https://github.com/rust-embedded/discovery/pull/255.
Link checking passes without any issues with the current release of `mdbook`:
```bash
$ mdbook --version
mdbook v0.4.8
$ mdbook build
2021-05-31 22:34:19 [INFO] (mdbook::book): Book building has started
2021-05-31 22:34:19 [INFO] (mdbook::book): Running the html backend
$ linkchecker book
INFO linkcheck.cmdline 2021-05-31 22:34:25,644 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.0.1
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors
LinkChecker …
```
> Remove exemption for print.html from link checking

- src/05-led-roulette/debug-it.md
Linkchecker warned about this link to a directory without a trailing slash. Seen while working on https://github.com/rust-embedded/discovery/pull/346.
Link checking now completes without any warnings:
```bash
$ mdbook build
2021-05-31 22:49:44 [INFO] (mdbook::book): Book building has started
2021-05-31 22:49:44 [INFO] (mdbook::book): Running the html backend
$ linkchecker book
INFO linkcheck.cmdline 2021-05-31 22:49:55,452 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.0.1
[...]
Start checking at 2021-05-31 22:49:55+002
10 threads active,   162 links queued,  205 links in 377 URLs checked, runtime 1 seconds
Statistics:
Downloaded: 2.15MB.
Content types: 34 image, 87 text, 0 video, 0 audio, 158 application, 0 mail and 170 other.
URL lengths: …
```
> Clean up warning from linkchecker

- src/05-led-roulette/flash-it.md
The file keeps on being referred to as either `cargo/config.toml` or `.cargo/config.toml`. This PR corrects all of them to `.cargo/config.toml`
> Fixed typos regarding `.cargo/config.toml`

- src/07-registers/rtrm.md
This is a minor change in the RTRM Section 7.1 which makes it easy to find the BSRR register.
The way we can reach to BSRR register and it's offset value 0x18.
> DOC Minor fixes

- src/03-setup/README.md
- src/11-usart/Cargo.toml
- src/11-usart/auxiliary/Cargo.toml
- src/11-usart/auxiliary/src/lib.rs
- src/11-usart/auxiliary/src/monotimer.rs
- src/11-usart/buffer-overrun.md
- src/11-usart/examples/buffer-overrun-timed.rs
- src/11-usart/examples/buffer-overrun-txe.rs
- src/11-usart/examples/buffer-overrun.rs
- src/11-usart/examples/echo.rs
- src/11-usart/examples/receive-a-single-byte.rs
- src/11-usart/examples/reverse-string.rs
- src/11-usart/examples/the-answer.rs
- src/11-usart/my-solution.md
- src/11-usart/receive-a-single-byte.md
- src/11-usart/reverse-a-string.md
- src/11-usart/src/main.rs
- src/11-usart/uprintln.md
This is an alternate version of #267 which fixes the panic by bumping dependencies. It also addresses the previously unsafe access to the USARTs transmit and receive data registers (TDR and RDR, https://github.com/stm32-rs/stm32-rs/pull/558) by bumping the BSP to the brand spanking new release 0.7.0 which comes with a fixed PAC and HAL. Thank you very much @adamgreig, @Sh3Rm4n, and @rubberduck203 for your patience and support along this journey!
This PR also bumps non-critical dependencies to their actual releases. For example `heapless`, which makes use of const generics nowadays.
I did not succeed in getting `mdbook test` to actually check the example code. I moved it over to the `examples` directory and included it in the Markdown files so that it can be checked with `cargo build …
> Fix and clean up 11-usart by bumping dependencies

- src/05-led-roulette/auxiliary/Cargo.toml
- src/05-led-roulette/auxiliary/src/lib.rs
- src/05-led-roulette/debug-it.md
- src/05-led-roulette/examples/my-solution.rs
- src/05-led-roulette/examples/the-led-and-delay-abstractions.rs
- src/05-led-roulette/my-solution.md
- src/05-led-roulette/the-led-and-delay-abstractions.md
This PR brings the LED roulette to up-to-date dependencies and factors out the examples, so that they could be tested in CI.
I wanted to update all examples at once in the first place. But this did not get to the pace I wanted, so I will attempt this one after another.
> Streamline LED roulette example

- src/03-setup/linux.md
The package `arm-none-eabi-gdb` is no longer provided by Fedora as stated in #364. So let's guide Fedora uses to _Other distros_ then and use a pre-built toolchain provided by ARM. This is also the recommendation from the [issue at Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1859627#c26).
> Fix instructions for installting GDB on Fedora

- src/05-led-roulette/the-challenge.md
The text said to modify `../.cargo/config.toml`, but the command was given to modify `../openocd.gdb`.
> Fix typo in 05-led-roulette/the-challenge

- src/03-setup/linux.md
- src/03-setup/verify.md
Updates  Fedora instructions and Verification steps for *Nix where versions of OpenOCD (0.11.0 in Fedora 33's case) have a single `interface/stlink.cfg` supporting all ST-LINK versions.
- Closes #364
> Update Fedora and Linux verification steps

- src/08-leds-again/the-solution.md
Since the read value is ignored, using `modify` seems redundant. 
Also, `modify` isn't mentioned in the text prior this chapter, while `write` is explained.
> 8.3: Use `write` instead of `modify`

- src/04-meet-your-hardware/terminology.md
- src/SUMMARY.md
I feel like a more fleshed out terminology section is both necessary and fits into chapter 4 better than chapter 5, especially since
we are now dealing with BSPs as well.
> Terminology section in chapter 4

- src/appendix/1-general-troubleshooting/README.md
- src/appendix/2-how-to-use-gdb/README.md
This mostly just deletes stuff since its related to OpenOCD which we don't have to use anymore with this rewrite (\o/).
I haven't come across any issues with this (that I haven't fixed upstream already) apart from the two things mentioned in the
README. I would expect that this file might grow over time though.
> Update the troubleshooting section for micro:bit

- src/03-setup/verify.md
Replaces dash with whitespace since the version if the dash is not working.
> Use `cargo embed` instead of `cargo-embed`

- src/03-setup/verify.md
- src/05-led-roulette/build-it.md
Adds `rustup target add *` to chapter 3 verification, but currently leaves the explanation in chapter 5 since the explanation fits better in there (it depends on explanations in ch4).
But if desired I can move everything around.
Fixes #401
> Add rustup target add to verification step and modify chapter 5 slightly

- src/04-meet-your-hardware/terminology.md
This allows us to deep link to them from other parts of the discovery book.
I've split this change out from #403 as it may be more contentious.
> Make terminology parts sub-sections

- microbit/src/05-led-roulette/debug-it.md
Change absolute link to relative since the current link is broken since it starts from the root level which is one above where it should be with the new structure.
> Fix broken link to c3

- microbit/src/03-setup/Embed.toml
- microbit/src/03-setup/verify.md
probe-rs 0.12 changed from accepting generic chip description ("nrf51822")
to requiring specific chip description (e.g. "nrf51822_xxAA").
According to dirbaio on probe-rs matrix "there's three nrf51822 variants
with different flash/ram sizes, AA/AB/AC.
AA is 256k flash, 16k ram, afaik all microbit v1's are AA"
Without this change, when I attempted the `cargo embed` step I got
`Error... Found multiple chips matching 'nrf51822', unable to select a single chip.`
> Use specific chip for micro:bit v1 board.

- microbit/src/03-setup/verify.md
- microbit/src/05-led-roulette/it-blinks.md
I forgot editing the book as well in #423.
BTW, I put the chip instructions in one line each so that people are not confused and uncomment also the "v2" comment. I saw somebody asking in the chat about this.
> Update micro:bit chip descriptions in the book

- .github/workflows/ci.yml
Hopefully fixes CI build failure see in #427.
> Run cargo-doc on relevant target instead of native

- microbit/src/03-setup/Embed.toml
- microbit/src/03-setup/verify.md
- microbit/src/05-led-roulette/Embed.toml
- microbit/src/05-led-roulette/it-blinks.md
- microbit/src/07-uart/Embed.toml
- microbit/src/08-i2c/Embed.toml
- microbit/src/09-led-compass/Embed.toml
- microbit/src/10-punch-o-meter/Embed.toml
> Use more specific chip spec for micro:bit v2

- f3discovery/src/03-setup/README.md
Fixed error: unknown argument '-version', did you mean '--version' when executing 'cargo size -- -version'.
> Fixed "cargo size" argument

- microbit/src/07-uart/Cargo.toml
- microbit/src/07-uart/my-solution.md
- microbit/src/08-i2c/Cargo.toml
- microbit/src/08-i2c/my-solution.md
- microbit/src/08-i2c/the-challenge.md
This pull request adds the `my-solutions.md` of chapter 7 and 8 to work with version 0.7.x of heapless. 
Changes:
- Use `heapless = "0.7.10"` (because why not? I can leave it out if necessary)
- Use const generics with heapless (the `my-solutions.md` got left behind in #432)
- Use `core::str::from_utf8()` instead of `heapless::String::from_utf8()`, because the latter one [got removed](https://github.com/japaric/heapless/blob/3b2bc421a06c083dc71bd66c73f0d98f5976e0cb/CHANGELOG.md?plain=1#L123) in heapless `heapless = "0.7.x"`
> Update my-solutions in chapters 7 & 8 to working solutions (issues with heapless)

- microbit/src/03-setup/README.md
This pull request updates the minimal Rust toolchain version required for microbit projects.
I had trouble compiling the microbit projects recently. After some research, I found out the `fixed` crate was updated to version `1.12.0` recently, and as stated on the [front page from the crate in crates.io](https://crates.io/crates/fixed), now requires Rust toolchain version 1.57.0 or higher.
This forces to have a Rust toolchain version >= 1.57.0 in order to compile the various projects for microbit v1 and v2.
> Change minimal Rust toolchain version

- microbit/src/09-led-compass/solution-2.md
- microbit/src/09-led-compass/take-2.md
The arguments of [atan2f](https://docs.rs/libm/latest/libm/fn.atan2f.html) are swapped. The first argument should be `y`, and the second should be `x`. This caused a mismatch between the axis in `take-1.md` and take-2.md`, where in take-1 the north is up, and in take-2 the north is on the right side. Also rotation was flipped because of this.
Swapping the arguments of `atan2f` to match the documentation solves the problem, but the if-else chain needed some adjustment as well.
> Fix wrong usage of atan2f

- f3discovery/src/05-led-roulette/the-led-and-delay-abstractions.md
I got stuck at point 5.4.  trying to enter ```(gdb)``` commands. 
As this is a beginner friendly book, suggesting adding a note that you need debugger active for (gdb) commands. 
e.g. ```(gdb) target remote :3333``` or ```load```
Won't work without openocd being active in a separate window.
> Added note in the-led-and-delay-abstractions,

- microbit/src/05-led-roulette/light-it-up.md
micro:bit v2 schematic image cannot be displayed normally because the github storage path has changed
> fix 05-led-roulette light-it-up.md

- src/README.md
Up to now, the module of [microbit](https://jzow.github.io/discovery/microbit/index.html) new version book has been translated complete and is being translated for the old version of f3d，I have proofread it twice.
F3d data is expected to be translated in 3-5 working days.
By the way, some html tags in the book are not properly marked/closed, such as`<video/>`, some places use `&quot;` symbols, not used in some places.
> Add Chinese translation

- microbit/src/03-setup/README.md
Fixes: #479
Given that the prerequisites are relatively complex (depends on the OS), I preferred to link to them instead of trying to give specific instruction for all OSes. Hopefully, that should be enough for most learner, since the prerequisites section is pretty clearly marked
> Add cargo-embed prerequisite

- f3discovery/src/05-led-roulette/the-led-and-delay-abstractions.md
Fixes two typos in the LED Roulette section:
`creating` => `create`
`it's` => `its`
> Issue #483 fix typos in roulette section ✍️

- microbit/src/05-led-roulette/Cargo.toml
- microbit/src/05-led-roulette/examples/my-solution.rs
- microbit/src/05-led-roulette/my-solution.md
* Let's lower the bar four young players and have a working reference right out of the repository
* I could be put into action with `cargo-flash` with one of the following invocations:
```
$ cargo flash --example my-solution --features v2 --target thumbv7em-none-eabihf --chip nrf52833_xxAA
$ cargo flash --example my-solution --features v1 --target thumbv7em-none-eabihf --chip nrf51822_xxAA
```
> Factor out micro:bit LED roulette into turn-key example

- microbit/src/03-setup/README.md
Currently, the link pointing to `cargo-embed`'s prerequisites shows a redirection message: "cargo-embed has moved repository".
To ease the process of setting up the development environment, this PR replaces the outdated link by current a one. I'm not entirely sure if the updated link is the best one available, so feel free to substitute a more suitable one.
> Fix link to cargo-embed prerequisites

- f3discovery/src/.cargo/config.toml
- f3discovery/src/05-led-roulette/flash-it.md
Let `cargo run` be more seamless and automated in our shared F3discovery cargo configuration.
Make it clear that we expect OpenOCD to be running for this to work.  Yes, this is clarified in the book but a bit of redundant help might be welcome by newbies.
> f3discovery: the gdb runner should reference our shared config

- f3discovery/src/03-setup/macos.md
- microbit/src/03-setup/macos.md
https://github.com/ARMmbed/homebrew-formulae has not been updated for more than a year at this point, and does not include native binaries for arm64 Macs.
As far as I can tell, mainline cask uses the same source for binaries but is (more) up to date.
I also took the liberty to update `f3discovery` version of the page to match layout of (more recently updated) `microbit` one — feel free to revert if necessary.
Thank you for your work on the book!!
> Change MacOS instructions to use ARM GCC from mainline cask

- microbit/src/03-setup/README.md
- microbit/src/05-led-roulette/debug-it.md
Closes #515
I decided to not include a note about checking `cargo-embed` version in case `monitor reset` does not work, version range should be enough imo.
> Bump `cargo-embed` version in setup to 0.18.0

- microbit/src/03-setup/README.md
Text instructions specify installing `cargo-embed` v0.18.0 but code block incorrectly shows installing v0.11.0
Fixes #526
> Fix pkg version: Update setup/README.md

- microbit/src/03-setup/README.md
Just continuing the dead link whac-a-mole game from #509. Happy to modify links/text if these are the wrong ones
> Update cargo-embed links

- f3discovery/src/03-setup/macos.md
- microbit/src/03-setup/macos.md
Older instructions are no longer valid.
> Update instructions for install gdb on macOS, address issue # 540

- f3discovery/src/11-usart/README.md
This is a small change. 
I was running into issues with serial comms not coming back from my microcontroller, despite verifying that OpenOCD, itmdump, minicom/PuTTY were working correctly, and the actual pin selection was correct for my board revision. 
It turns out I had misinterpreted this line in 11-usart/README.md:
> Everything is already wired on the board so you don't need to wire anything yourself.
I understood this as a continuation of 10-serial-communication/loopbacks.md, where I had just shorted the PC4 and PC5 pins. I thought "already wired" meant that the PC4-PC5 wire was necessary. This loopback, of course, ends up breaking the Virtual COM Port.
I've added a couple additional lines to ensure others don't run into this same issue, by clarifying the need to remove the wires …
> Clarifying documentation in USART chapter.

- microbit/src/03-setup/IDE.md
- microbit/src/SUMMARY.md
I had some troubles using IntelliJ to work with the code examples.  I thus added a page that tries to help the user getting the best out of their IDE with this book.
Some of the solution are not IntelliJ specific, so I separated this page into a general purpose help and a section that concern specific IDE.
Since I only use IntelliJ, I can't provide section for Code, for examples. So, I invited users of other IDE to contribute.
Ideally, I'd love for someone to get how to use the debugger with the IDE too. However, even if this page is not perfect, I believe it may still be an improvement for the next reader
> NF: add an IDE help

- f3discovery/src/03-setup/README.md
- microbit/src/03-setup/README.md
https://github.com/rust-lang/rustup/pull/3578
> 'llvm-tools-preview' component is now named 'llvm-tools'

- microbit/src/03-setup/README.md
- microbit/src/03-setup/verify.md
Cargo-embed by it self has been deprecated, and has been included in probe-rs instead, update the documentation to install `probe-rs-tools` instead of `cargo-embed`, and added some command line tests to show how to test if probe-rs can see the micro:bit
> Migrate to probe-rs-tools

- microbit/src/03-setup/linux.md
- microbit/src/03-setup/verify.md
Update udev rules to fit better with modern systems.
Updated the udev rules to use the `uaccess` tag instead of the `MODE` and `GROUP` modifiers, as that is deprecated.
Renamed the udev rule file to start with 69 instead of 99, so it gets loaded before user access rules are loaded for `uaccess` permissions, which is run in 73-seat-late.rules (provided by systemd).
Added text showing how to test for these `uaccess` permissions.
Attached the udev rules file: [69-microbit.txt](https://github.com/user-attachments/files/15748644/69-microbit.txt)
> Update udev rules 

- microbit/src/03-setup/README.md
See #579. Maybe not the ultimate solution, but should at least triage the situation.
> updated probe-rs-tools instructions

- microbit/src/03-setup/macos.md
I noticed while going through the discovery book (that uses a micro:bit controller), that I could not run the `lsusb` command provided after the setup section. It looks like on MacOS, this bin isn't there by default and also needs to be installed with `brew`, so this PR adds that command to the MacOS-specific installation steps.
>  MacOS install instructions - lsusb

- microbit/src/07-uart/Cargo.toml
- microbit/src/07-uart/Embed.toml
- microbit/src/07-uart/src/main.rs
- microbit/src/07-uart/src/serial_setup.rs
Context: With recent updates to Rust’s embedded libraries, compatibility issues arose due to older versions of embedded-hal and associated dependencies. This refactor updates the project to utilize the latest libraries, ensuring both compatibility and enhanced functionality.
Key Refactoring Points:
1. Updated Serial Communication:
- Replaced the existing embedded-hal serial interfaces with the updated embedded-hal-nb::nb and embedded-hal-nb::serial modules, as well as embedded-io.
This update aligns the project with the latest embedded-hal standards, enhancing future compatibility and maintaining consistency with the broader embedded Rust ecosystem.
use embedded_hal_nb::nb;
use embedded_hal_nb::serial::{Error as SerialError, ErrorType, Read, Write};
use embedded_io::{Read as …
> 07-uart code refactor

- src/README.md
Hi! Since we at Espressif have something similar to the discovery books, but in a different format, I thought that it might be worth mentioning the resources in the discovery book. 
If you want to keep this for the current content only, feel free to close the PR. Also, not sure if the format in which I added it, is the best, so also open to any suggestions!
> Add Rust on Espressif discovery journey

- f3discovery/book.toml
- microbit/book.toml
See the [mdbook documentation](https://rust-lang.github.io/mdBook/format/configuration/general.html)
Apparently the `author` was field was [incorrect documentation](https://github.com/rust-lang/mdBook/issues/2623)
> rename the `author` field to `authors` in book.toml

- README.md
- src/README.md
Update the READMEs to mention the latest discovery book (https://docs.rust-embedded.org/discovery-mb2).
> Mention the latest discovery book

- microbit/src/11-snake-game/src/game.rs
The two lines removed don't seem to be used for any real purpose.
> remove unused code

- microbit/src/06-serial-communication/minicom-on-macos.md
- microbit/src/06-serial-communication/nix-tooling.md
- microbit/src/SUMMARY.md
I had trouble using **minicom** because it's not obvious which keyboard key corresponds to **Meta.** I tried various keys such as CNTRL, CMD, & Option but nothing worked.
I found that the Meta key is **ESC**  by running minicom in setup mode using `$ minicom -s`
* I created a new page called `macos-meta.md`
* I added a link to it at the end of `nix-tooling.md`
> added instructions for finding Meta key on MacOS
