src/03-setup/README.md
src/03-setup/linux.md
src/03-setup/macos.md
src/03-setup/windows.md

Fixed some 404 issues

---

ci/docker/x86_64-unknown-linux-gnu/Dockerfile
ci/run.sh
src/03-setup/verify.md
src/06-hello-world/README.md
src/12-bluetooth-setup/README.md
src/12-bluetooth-setup/linux.md
src/13-serial-over-bluetooth/README.md
src/appendix/1-general-troubleshooting/README.md

run linkchecker

---

src/06-hello-world/README.md

There was a tiny typo with file names.

fix(hello world): Changed 05-hello-world to 06-hello-world

---

src/05-led-roulette/debug-it.md
src/05-led-roulette/flash-it.md
src/05-led-roulette/my-solution.md
src/05-led-roulette/the-challenge.md
src/05-led-roulette/the-led-and-delay-modules.md

A few tiny grammar mistakes, also added a few tips and comparisons. Feel free to take what you like.

led-roulette: Fix some wording and add few tips

---

src/05-led-roulette/debug-it.md
src/06-hello-world/panic.md
src/17-async-io-the-future/more-challenges.md

Changes the word "tough" to "though" in a couple places.

Corrects spelling error changing tough to though

---

src/10-serial-communication/README.md

Added a missing word. It could be 'you' or 'we', I went with 'we' to make us all feel a little less alone in this world.

Fixes typo.

---

src/11-usart/send-a-single-byte.md

Updates chapter number.

---

src/14-i2c/lsm303dlhc.md

Fixes some awkward wording and adds a missing colon.

Fixes small typos.

---

src/16-punch-o-meter/gravity-is-up.md
src/16-punch-o-meter/src/main.rs

Code didn't match docs. `FACTOR` changed to `SENSITIVITY`. Also a small typo fix.

Updates code to match docs.

---

src/03-setup/windows.md

[as suggested by /u/szabot](https://www.reddit.com/r/rust/comments/80doqg/discovery_discover_the_world_of_microcontrollers/duutdn4/)

fix link; suggest gnu-mcu-eclipse/openocd

---

src/05-led-roulette/the-led-and-delay-abstractions.md

Fix sample code entry point in LED abstraction

---

.travis.yml
ci/install.sh

should fix the build
r? @rust-embedded/resources
cc @andre-richter

install a newer gcc

---

.travis.yml
src/03-setup/README.md
src/11-usart/Cargo.toml

also recommend readers to use the beta channel
r? @rust-embedded/resources (anyone)

CI: test on beta

---

src/01-background/README.md

Humidy => humidity
Much less components => many fewer components

Fix minor typos

---

src/README.md

Fixes typo on first page (intent => intend) #

---

src/10-serial-communication/README.md

Changing a word ('when' to 'went') that I believe was a typo.

Replaced a word in the readme to improve clarity

---

src/10-serial-communication/nix-tooling.md

Correct the /dev/ttyUSB0 permissions, and add note about udev rules

10-serial-communication/nix-tooling.md /dev/ttyUSB0 permissions

---

src/12-bluetooth-setup/at-commands.md

Hello japaric.
As you know I am thoroughly enjoying your tutorial :)
I wanted to offer some help completing this section. Also are the green and yellow wires that are connected to the FTDI in this diagram (assets/bluetooth-serial.png) backwards?
Cheers,
pegomes

Revisions to section 12.3 AT commands

---

src/03-setup/linux.md

Related: https://github.com/rust-embedded/book/pull/179

Install openocd package from the repository for ArchLinux

---

src/05-led-roulette/flash-it.md

I encountered some confusion while working through section 5.2 "Flash It", so I've added some updates that future readers might find useful 🙏

LED Roulette: Update 'flash it' docs

---

src/11-usart/buffer-overrun.md

This should fix a minor typo. 
Many thanks for this book, it's incredibly helpful!

Fix typo in chapter 11

---

src/10-serial-communication/README.md

As someone new to embedded programming, I found the term "serial communication protocol" confusing because in the general sense there are many "serial communication protocols" which have nothing to do with the specific logical protocol referenced in the book (e.g. MIDI).
Providing a link to the "Aynchronous Serial Communication" page on Wikipedia will hopefully spare others from having to search the web to find out just which "serial communication protocol" is being referenced.

Link to the Wikipedia page on Asynchronous Serial Communication

---

src/14-i2c/read-several-registers.md

Fixed a register name in comments of read-several-register.md

Fixed a comment

---

src/12-bluetooth-setup/linux.md

Typo Mistake Correction

---

book.toml

Metadata taken from https://github.com/rust-embedded/discovery/blob/master/README.md
Fixes #209

Add `book.toml` file

---

src/03-setup/README.md

Fix broken link for L3GD20 gyroscope datasheet

---

src/README.md

Fixes #192.
Like the issue author, I was not sure what "Rustic" meant, but also what is meant by "low-level" is relative. Thus, let's specify that we won't go into detail about the link script/boot process.

Removed ambiguous wording in introduction.

---

src/explore.md

Closes #231 
This is part of the cleanup described in this issue:
https://github.com/rust-embedded/discovery/issues/231

Rework the "where to go from here" section to track items we want to teach

---

src/15-led-compass/calibration.md

Update link to eCompass calibration note

---

src/08-leds-again/configuration.md

I think it sounds better this way...

Reword the sentence in configuration.md

---

src/10-serial-communication/nix-tooling.md

Makes it easier to read, I think.

Small fix in nix-tooling.md

---

src/05-led-roulette/auxiliary/Cargo.toml
src/06-hello-world/auxiliary/Cargo.toml
src/07-registers/auxiliary/Cargo.toml
src/08-leds-again/auxiliary/Cargo.toml
src/09-clocks-and-timers/auxiliary/Cargo.toml
src/14-i2c/auxiliary/Cargo.toml
src/15-led-compass/auxiliary/Cargo.toml
src/16-punch-o-meter/auxiliary/Cargo.toml

This should fix issue #259 in all chapters except 11 and 16.

Upgrade most aux crates to cortex-m 0.6.3

---

src/01-background/README.md

I thought I'd have a go at some copy editing on the Background section.  If any of these changes look worthwhile, please let me know and/or feel free to point me at other sections.

A few suggested changes for the "Background" section

---

src/03-setup/README.md
src/14-i2c/lsm303dlhc.md

In response to  https://github.com/rust-embedded/discovery/issues/274#issuecomment-777245460
Please edit at leisure / suggest anything

add two notes flagging lsm303agr

---

src/06-hello-world/README.md

fix typo, link

---

src/05-led-roulette/debug-it.md
src/05-led-roulette/the-led-and-delay-abstractions.md

After doing 06-hello-world I felt some tweaks and cleanup
were needed in debug-it.md and the-led-and-delay-abstractions.md.

Tweak 05-led-roulette

---

src/07-registers/Cargo.toml
src/07-registers/auxiliary/Cargo.toml
src/07-registers/auxiliary/src/lib.rs
src/07-registers/bad-address.md
src/07-registers/openocd.gdb
src/07-registers/optimization.md
src/07-registers/spooky-action-at-a-distance.md
src/07-registers/type-safe-manipulation.md

Modified to run using `stm32f3-discovery` instead of `f3` and updated
the `.md` files appropriately.

New 07 Registers

---

README.md

Several questions have ended up in the issues recently. So what about pointing the discussions section out more prominently?

Guide to disussions and issues in README.md

---

src/04-meet-your-hardware/terminology.md
src/05-led-roulette/build-it.md
src/05-led-roulette/debug-it.md
src/07-uart/echo-server.md
src/07-uart/receive-a-single-byte.md
src/07-uart/send-a-single-byte.md
src/08-i2c/read-a-single-register.md
src/08-i2c/the-general-protocol.md
src/08-i2c/using-a-driver.md

Minor fixes and grammar changes on the micro:bit rewrite branch.

Typos and grammar changes

---

f3discovery/src/01-background/README.md

These changes solve some typos errors in the background file README.md
This will improve the readability of the file.

fix typos in background(README.md)

---

microbit/src/03-setup/Embed.toml
microbit/src/05-led-roulette/Embed.toml
microbit/src/07-uart/Embed.toml
microbit/src/08-i2c/Embed.toml
microbit/src/09-led-compass/Embed.toml
microbit/src/10-punch-o-meter/Embed.toml

This is the fix from #422 propagated to all chapters.

Fix micro:bit V1 chip specification everywhere

---

microbit/src/08-i2c/README.md
microbit/src/08-i2c/lsm303agr.md
microbit/src/08-i2c/read-a-single-register.md
microbit/src/08-i2c/the-general-protocol.md

The terms master/slave should not be propagated for future technologists to absorb. Made changes to text and images (some resizing may be necessary). I'm not sure this terminology is being used in subsequent chapters, but I'm more than happy to update them as I encounter them.

Updating Chapter 8 with more inclusive terms

---

f3discovery/src/15-led-compass/take-1.md

When I translate, the html syntax checks this error

Fix incorrect html tag syntax

---

src/README.md

Hi, I'm currently working on the Portuguese translation of this book and would like to add the link here. :)

translation: add pt-BR link

---

.vscode/settings.json

Created #528 before finding out the fix is much easier than I was imainging :)
Fixes #528

chore: add vs-code settings for enabling cargo features

---

src/README.md

fix broken links for pt-br translations

---

.github/workflows/ci.yml

Upgrade the ci version
